[workspace]
authors = ["Andrey Tatarinov <a@tatarinov.co>"]
channels = ["conda-forge"]
name = "webrtc-ros"
platforms = ["linux-aarch64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.11,<3.14"
py-spy = ">=0.4.0,<0.5"

[pypi-dependencies]
aiortc = ">=1.13.0, <2"
aiohttp = ">=3.12.13, <4"
