[workspace]
authors = ["Andrey Tatarinov <a@tatarinov.co>"]
channels = ["conda-forge", "robostack-kilted"]
name = "webrtc-ros"
platforms = ["linux-aarch64"]
version = "0.1.0"

[activation]
scripts = ["install/setup.sh"]

[tasks]
build = { cmd = "colcon build", inputs = ["src"] }
# build = {cmd="colcon build --symlink-install", inputs=["src"]}

debug_launch = {cmd = "ros2 launch webrtc_bridge debug.launch.xml", depends-on = ["build"]}

[dependencies]
ros-kilted-desktop = "*"
ros-kilted-usb-cam = "*"
ros-kilted-rosbridge-suite = "*"
python = ">=3.11,<3.14"
py-spy = ">=0.4.0,<0.5"
colcon-common-extensions = ">=0.3.0,<0.4"
pre-commit = ">=4.2.0,<5"

[pypi-dependencies]
webrtc-bridge = { path = "./src/webrtc_bridge" }
