[workspace]
authors = ["Andrey Tatarinov <a@tatarinov.co>"]
channels = ["conda-forge", "robostack-jazzy"]
name = "webrtc-ros"
platforms = ["linux-aarch64"]
version = "0.1.0"

[activation]
scripts = ["install/setup.sh"]

[tasks]
build = { cmd = "colcon build", inputs = ["src"] }
# build = {cmd="colcon build --symlink-install", inputs=["src"]}

[dependencies]
ros-jazzy-desktop = ">=0.11.0,<0.12"
ros-jazzy-usb-cam = ">=0.8.1,<0.9"
python = ">=3.11,<3.14"
py-spy = ">=0.4.0,<0.5"
colcon-common-extensions = ">=0.3.0,<0.4"

[pypi-dependencies]
webrtc-bridge = { path = "./src/webrtc_bridge" }
